swagger: "2.0"
info:
  title: API Documentation for Library
  description: Library Portal
  termsOfService: https://www.google.com/policies/terms/
  contact:
    email: contact@xyz.local
  license:
    name: BSD License
  version: v1
host: 127.0.0.1:8000
schemes:
  - http
basePath: /
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /api/docs/:
    get:
      operationId: api_docs_list
      description: ""
      parameters: []
      responses:
        "200":
          description: ""
      produces: []
      tags:
        - api
    parameters: []
  /api/redoc/:
    get:
      operationId: api_redoc_list
      description: ""
      parameters: []
      responses:
        "200":
          description: ""
      produces: []
      tags:
        - api
    parameters: []
  /api/schema/:
    get:
      operationId: api_schema_list
      summary: OpenApi3 schema for this API. Format can be selected via content negotiation.
      description: |-
        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters: []
      responses:
        "200":
          description: ""
      produces:
        - application/vnd.oai.openapi
        - application/yaml
        - application/vnd.oai.openapi+json
        - application/json
      tags:
        - api
    parameters: []
  /api/token/:
    post:
      operationId: api_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: "#/definitions/TokenObtainPair"
      responses:
        "201":
          description: ""
          schema:
            $ref: "#/definitions/TokenObtainPair"
      tags:
        - api
    parameters: []
  /api/token/refresh/:
    post:
      operationId: api_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: "#/definitions/TokenRefresh"
      responses:
        "201":
          description: ""
          schema:
            $ref: "#/definitions/TokenRefresh"
      tags:
        - api
    parameters: []
  /books:
    get:
      operationId: books_list
      description: Retrieve resource(s)
      parameters: []
      responses:
        "200":
          description: Successful Response
      tags:
        - books
    post:
      operationId: books_create
      description: Create a new reader with provided details.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            required:
              - reference_id
              - reader_name
              - reader_contact
              - reader_address
            type: object
            properties:
              reference_id:
                description: Reference ID of the reader
                type: integer
              reader_name:
                description: Name of the reader
                type: string
              reader_contact:
                description: Contact information of the reader
                type: string
              reader_address:
                description: Address of the reader
                type: string
              books:
                description: List of book IDs associated with the reader
                type: array
                items:
                  type: integer
      responses:
        "201":
          description: Reader created successfully
          schema:
            type: object
            properties:
              reference_id:
                description: Reference ID of the reader
                type: integer
              reader_name:
                description: Name of the reader
                type: string
              reader_contact:
                description: Contact information of the reader
                type: string
              reader_address:
                description: Address of the reader
                type: string
              books:
                description: List of book IDs associated with the reader
                type: array
                items:
                  type: integer
        "400":
          description: Bad Request
      tags:
        - books
    parameters: []
  /books/{id}:
    get:
      operationId: books_read
      description: Retrieve resource(s)
      parameters: []
      responses:
        "200":
          description: Successful Response
      tags:
        - books
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this book.
        required: true
        type: integer
  /books/{id}/delete:
    delete:
      operationId: books_delete_delete
      description: Delete a resource
      parameters: []
      responses:
        "204":
          description: Resource deleted successfully
      tags:
        - books
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this book.
        required: true
        type: integer
  /books/{id}/update:
    put:
      operationId: books_update_update
      description: Update a resource completely
      parameters:
        - name: data
          in: body
          required: true
          schema:
            description: Request body for updating a resource
            type: object
            additionalProperties: true
      responses:
        "200":
          description: Resource updated successfully
      tags:
        - books
    patch:
      operationId: books_update_partial_update
      description: Partially update a resource
      parameters:
        - name: data
          in: body
          required: true
          schema:
            description: Request body for partially updating a resource
            type: object
            additionalProperties: true
      responses:
        "200":
          description: Resource updated successfully
      tags:
        - books
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this book.
        required: true
        type: integer
  /readers:
    get:
      operationId: readers_list
      description: Retrieve resource(s)
      parameters: []
      responses:
        "200":
          description: Successful Response
      tags:
        - readers
    post:
      operationId: readers_create
      description: Create a new reader with provided details.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            required:
              - reference_id
              - reader_name
              - reader_contact
              - reader_address
            type: object
            properties:
              reference_id:
                description: Reference ID of the reader
                type: integer
              reader_name:
                description: Name of the reader
                type: string
              reader_contact:
                description: Contact information of the reader
                type: string
              reader_address:
                description: Address of the reader
                type: string
              books:
                description: List of book IDs associated with the reader
                type: array
                items:
                  type: integer
      responses:
        "201":
          description: Reader created successfully
          schema:
            type: object
            properties:
              reference_id:
                description: Reference ID of the reader
                type: integer
              reader_name:
                description: Name of the reader
                type: string
              reader_contact:
                description: Contact information of the reader
                type: string
              reader_address:
                description: Address of the reader
                type: string
              books:
                description: List of book IDs associated with the reader
                type: array
                items:
                  type: integer
        "400":
          description: Bad Request
      tags:
        - readers
    parameters: []
  /readers/{id}:
    get:
      operationId: readers_read
      description: Retrieve resource(s)
      parameters: []
      responses:
        "200":
          description: Successful Response
      tags:
        - readers
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this reader.
        required: true
        type: integer
  /readers/{id}/delete:
    delete:
      operationId: readers_delete_delete
      description: Delete a resource
      parameters: []
      responses:
        "204":
          description: Resource deleted successfully
      tags:
        - readers
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this reader.
        required: true
        type: integer
  /readers/{id}/update:
    put:
      operationId: readers_update_update
      description: Update a resource completely
      parameters:
        - name: data
          in: body
          required: true
          schema:
            description: Request body for updating a resource
            type: object
            additionalProperties: true
      responses:
        "200":
          description: Resource updated successfully
      tags:
        - readers
    patch:
      operationId: readers_update_partial_update
      description: Partially update a resource
      parameters:
        - name: data
          in: body
          required: true
          schema:
            description: Request body for partially updating a resource
            type: object
            additionalProperties: true
      responses:
        "200":
          description: Resource updated successfully
      tags:
        - readers
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this reader.
        required: true
        type: integer
definitions:
  TokenObtainPair:
    required:
      - username
      - password
    type: object
    properties:
      username:
        title: Username
        type: string
        minLength: 1
      password:
        title: Password
        type: string
        minLength: 1
  TokenRefresh:
    required:
      - refresh
    type: object
    properties:
      refresh:
        title: Refresh
        type: string
        minLength: 1
      access:
        title: Access
        type: string
        readOnly: true
        minLength: 1
