# Generated by Django 5.0.7 on 2024-07-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='books',
            field=models.ManyToManyField(related_name='readers', to='lims_app.book'),
        ),
    ]
